version: '3.7'

services:

  frontend:
    build:
      context: ../packages/frontend/
      dockerfile: Dockerfile
    volumes:
      - '/app/node_modules'
      - '../packages/frontend:/app'
    ports:
      - 3000:3000

  backend:
    build:
      context: ../packages/backend/
      dockerfile: Dockerfile
    volumes:
      - '/app/node_modules'
      - '../packages/backend:/app'
    ports: 
      - 3001:3001
    environment: 
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}