version: '3.7'

services:

  frontend:
    build:
      context: ../packages/frontend/
      dockerfile: Dockerfile
    volumes:
      - '/app/node_modules'
    ports:
      - 3000:3000

  backend:
    build:
      context: ../packages/backend/
      dockerfile: Dockerfile
    volumes:
      - '/app/node_modules'
    ports: 
      - 3001:3000